import intf_libs += libbacktrace%lib{backtrace}

lib{crails-design-patterns}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

hxx{export}@./: cxx.importable = false

cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBCRAILS_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBCRAILS_SHARED_BUILD

lib{crails-design-patterns}:
{
  cxx.export.poptions = "-I$out_root/libcrails-design-patterns/" "-I$src_root/libcrails-design-patterns"
  cxx.export.libs = $intf_libs
}

liba{crails-design-patterns}: cxx.export.poptions += -DLIBCRAILS_STATIC
libs{crails-design-patterns}: cxx.export.poptions += -DLIBCRAILS_SHARED

if $version.pre_release
  lib{crails-design-patterns}: bin.lib.version = "-$version.project_id"
else
  lib{crails-design-patterns}: bin.lib.version = "-$version.major.$version.minor"

{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = true
}
